Algebraic-Programming/ALP

include/graphblas/reference/matrix.hpp, include/graphblas/utils/iscomplex.hpp, include/graphblas/utils/parser/MatrixFileIterator.hpp, include/graphblas/utils/parser/MatrixFileProperties.hpp, include/graphblas/utils/parser/MatrixFileReader.hpp, include/graphblas/utils/parser/MatrixFileReaderBase.hpp
This MR modifies the parser to read MatrixMarket files that hold complex-valued nonzeroes, and furthermore handles Hermitian matrix files correctly. Complex values are read into the C++ `std::complex` type, which also provides the required complex conjugation operation.
This MR paves the way for smoke tests of existing iterative solvers using complex-valued system matrices. This unit test will be added via later MR(s). This MR also updates the coding style of the affected files.
=> Resolve internal issue 401: parse complex input and interpret hermitian stored in upper triangle

include/graphblas/base/init.hpp
Some confusion regarding the non-blocking mode and `grb::init` caused due to somewhat stale documentation in its specification. This MR updates the descriptions, and furthermore repeats their deprecation warnings rather immediately at the top of each of the documentations.
Also some minor code style fixes.
=> Improve documentations of the deprecated grb::init and grb::finalize

include/alp/reference/matrix.hpp, include/alp/smf.hpp, tests/unit/CMakeLists.txt, tests/unit/dense_matrix_access.cpp
This exposes a const and non-const getter.
Add a unit test for matrix element access.
=> Add a getter for a reference to an element in matrix

include/graphblas/reference/vector.hpp
Bugfix: Makes the new `wrapRawVector` work even if the Coordinates class of the output vector does not match the default one of the reference implementation. This is needed for the backends that degelate some functionalities to `reference` or `reference_omp`.
=> Resolves internal issue #440

include/graphblas/base/blas1.hpp, include/graphblas/bsp1d/blas1.hpp, include/graphblas/reference/blas1.hpp, include/graphblas/reference/io.hpp, tests/unit/launcher/reduce.cpp
Aristeidis detected that when giving a dense descriptor and a sparse vector to `grb::foldl` (vector to scalar reduction), that the resulting code will complete the requested computation. It was instead intended, like with other primitives, that `ILLEGAL` is returned instead since the programmer promises a certain property that does not hold in practice.
This is conform the intent that the dense descriptor 1. prevents the generation of code that handles sparse cases, and 2. achieves (minor) performance benefits as it can skip some of the associated checks for sparsity.
This MR ensures the intended behaviour is what occurs. It also:
- reduces some code duplication throughout the code base;
- removes grb::Phase as an argument to reduction to a scalar, since the output is not a container;
- …
=> Resolves internal issues 441 and 311: missing run time checks to confirm density when dense descriptor is given to foldl (vector to scalar)

include/alp/base/vector.hpp, include/alp/reference/blas1.hpp, include/alp/reference/blas2.hpp, include/alp/reference/blas3.hpp, include/alp/reference/matrix.hpp, include/alp/reference/vector.hpp, include/alp/vector.hpp
Vector is implemented as a Nx1 Matrix behind the scenes and reuses existing mechanisms present in Matrix class.
=> Resolve internal issue 445: update dense reference vector implementation

include/graphblas/reference/coordinates.hpp, include/graphblas/reference/io.hpp
This MR contains the following changes:
- bugfix: an earlier MR moved the `grb::set` functions of the reference and reference_omp backends to `reference/io.cpp`, but did not update the parallelisation guards.
- code improvement: rely on `config::OMP::localRange` instead of parallel-for with a chunked static schedule. In several cases related to calls to `grb::set` and vector construction this leads to significant speedups.
This resolves internal issue 472 and contributes to internal issue 479.
Thanks to Alberto Scolari for contributing!
=> 472 grb set does not execute in parallel

include/graphblas/banshee/blas3.hpp, include/graphblas/reference/blas1.hpp, include/graphblas/reference/blas2.hpp, include/graphblas/reference/blas3.hpp, include/graphblas/reference/coordinates.hpp, include/graphblas/reference/io.hpp
In the `reference_omp` backend, as part of the previous merge into develop (#35), Alberto detected that increasing the chunk size of statically-scheduled parallel-for loops could increase the performance noticeably.
The intent of the previous chunk size was to prevent false sharing effects by considering a unit of loop iterands considered by OpenMP to be at least of some size `k`, where `k` is the cache line size. The idea was that then no threads will cause more than O(1) false sharing effects, even if the loop touches single-byte elements-- or indeed zero such effects in the case all memory regions are aligned.
However, despite its name, the OpenMP chunked static schedule introduces a run-time component by assigning the chunks to threads in a round-robin fashion-- aside from run-time …
=> 479 openmp chunked static parallel for does not do the intended thing

include/graphblas/reference/blas1.hpp
In eWiseMulAdd's polyalgorithm, the dense variant implements the case where the call generates dense output, but supports to cases regarding the output vector:
1) on entry the output vector was dense, or
2) on entry the output vector was totally empty.
The switch on these two cases was handled by `z_assigned` Boolean template argument, but in fact when true was assigning directly to the value arrays of the output vector, which is valid in the case where z initially was empty. Hence `assign_z` (or something like `z_was_empty`) is a more correct name.
This MR changes `z_assigned` into `assign_z` and joins it with some minor code style fixes.
The dispatcher furthermore determines the value of `assign_z` based partially on duplicate code. While if `sparse` is set `z_assign` is not used, this …
=> Issue #487: rename z_assigned to z_assign

include/graphblas/SynchronizedNonzeroIterator.hpp, include/graphblas/reference/compressed_storage.hpp, include/graphblas/reference/matrix.hpp, tests/unit/matrixIterator.cpp
Anders reported that copy-assignment of matrix output iterators was not properly implemented -- the local nonzero cache was not updated. The same was true for the copy-constructor, move-constructor, and move-assignment. This MR:
1. fixes all those issues, and 
2. hardens the matrixIterator unit test to test all four of {move,copy}x{assignment,construction} for all combination of pattern- and non-pattern matrices it already was testing for.
Additionally,
3. The assignment operators of the pattern-matrix output iterator specialisation did not return a reference to itself, with this MR also fixed;
4. the matrix output iterator itself now also adheres to the ALP matrix iterator API-- i.e., it defines an i, j, and v member function that return the row, column, and value of a nonzero, …
=> 462 copy move assigment of compressed storage iterator is missing the nonzero variable

include/graphblas/algorithms/bicgstab.hpp, include/graphblas/utils.hpp, tests/performance/fma.cpp, tests/smoke/smoketests.sh, tests/unit/CMakeLists.txt, tests/unit/add15d.cpp, tests/unit/add15m.cpp, tests/unit/dense_spmv.cpp, tests/unit/equals.cpp, tests/unit/unittests.sh, tests/unit/vmxa.cpp
Anders reported that the `tests/unit/dense_spmv.cpp` failed verification for `ecology2.mtx`. The reason was that the test relies on `grb::utils::equals` to compare numbers vs. an absolute error bound, however, the utility function is written for relative error checking. This MR clarifies the documentation of `grb::utils::equals', and hardens its API somewhat to prevent misuse.
Summarising, this MR:
- implements an absolute error check for `dense_spmv.cpp` instead of relying on `grb::utils::equals`;
- bugfix: BiCGstab also relied on `grb::utils::equals` while it should not;
- bugfix `grb::utils::equals`: the given relative bound was interpreted twice as loose;
- bugfix `grb::utils::equals`: overflow of the normalisation factor was handled questionably;
- testing: unit test added for …
=> 464 dense spmv test does not work for ecology2 mtx

include/graphblas/reference/blas1.hpp, include/graphblas/reference/blas2.hpp, include/graphblas/reference/coordinates.hpp, include/graphblas/reference/io.hpp, include/graphblas/reference/matrix.hpp
This MR reviews all uses of the dynamic schedule and replaces it with a static schedule (through `grb::config::OMP::localRange`) in case the loop is determined to be regular. In all irregular loop cases, documentation has been added with rationale as per the schedule choice, as well as for cases where the choice is not clear-cut.
This MR also modifies the following unrelated behaviour:
- eWise{Map,Lambda} no longer serialise lambda invocations when `_DEBUG` is defined. Rationale: if this is desired, the user can add this to the lambda itself-- by default, it is desirable that lambdas run concurrently in order to diagnose any data race issues, for example.
As always, this MR includes some code style fixes throughout all files touched.
=> 490 dynamic scheduling for regular loop

include/graphblas/bsp1d/exec.hpp, include/graphblas/bsp1d/io.hpp, include/graphblas/bsp1d/pinnedvector.hpp, include/graphblas/reference/coordinates.hpp, include/graphblas/reference/pinnedvector.hpp, tests/unit/CMakeLists.txt, tests/unit/pinnedVector.cpp, tests/unit/unittests.sh
Aristeidis and Anders reported an issue where combinations of `clear`, `setElement`, and usage of the `PinnedVector` could segfault for the `reference` and `reference_omp` backends. This MR first and foremost introduces a unit test for the `PinnedVector` that operates on vectors of `double`s, vectors of `std::pair`s, and tests it using both the SEQUENTIAL and PARALLEL I/O modes.
This added unit test found or confirmed the following issues, which this MR also fixes:
- `grb::set` (BSP1D) contains code to handle the `use_index` descriptor, but this code should only pass by the compiler if `size_t`s are convertible into the vector element type;
- `grb::PinnedVector` constructor (reference, reference_omp, and BSP1D) should pin the stack, not the bitmask;
- `grb::clear` (BSP1D) did not undo the …
=> 422 clear setelement and usage of pinnedvector leads to segementation fault

.gitlab-ci.yml, CMakeLists.txt, changelog.md, docs/Suppressions.md, docs/doxy.conf, include/graphblas/internalops.hpp, include/graphblas/reference/blas1.hpp, include/graphblas/reference/compressed_storage.hpp, include/graphblas/utils/suppressions.h
Final tests are likely to pass. This MR will stage the current release candidate into develop in preparing its push to master.
=> Merge v0.6.0 rc1

tests/performance/performancetests.sh
This MR prints a warning when the auto-detection of the number of sockets for performance tests fails, and selects a nonzero default instead (i.e., 1). The previous behaviour silently selected 0 sockets on detection failure instead, which would result in performance tests for the hybrid backend to not run.
=> Resolves internal issue #322: number of sockets detection on some machines fails

include/graphblas/base/blas2.hpp, include/graphblas/reference/blas2.hpp
In sparse matrix--vector multiplication, there was disabled code detecting whether the output and output mask were the same vector. When considering the scattering SpMV multiplication, which consists of a loop of updates to the output vector, in such an overlapping case the intermediate scatters would overwrite the mask, potentially altering it during the multiplication. Therefore surely this overlap must be illegal (as it also is defined in the code documentation as well as the initial ALP/GraphBLAS paper), and the overlap check must be re-enabled.
This MR makes indeed re-enables the check, and revises the documentation of `grb::mxv` and `grb::vxm` in `base/blas2.hpp` to bring it up to date with the current state, and in particular with regards to the overlap detection and the …
=> Resolve internal issue #137: re-enable overlap detection between output vector and output mask

include/alp/reference/matrix.hpp, tests/unit/CMakeLists.txt, tests/unit/dense_outer.cpp
Also, re-enable and improve outer unit test
=> Update Functor-based matrices according to the recent AMF changes

docs/Suppressions.md, include/graphblas/reference/blas1.hpp, tests/unit/launcher/reduce.cpp
This is a regression compared to earlier versions that did accept reducing a sparse vector into a single scalar, using a Monoid structure-- earlier commits reviewed the behaviour under the dense descriptor, but erroneously made fold-into-scalars require dense always. This MR fixes this to only return `ILLEGAL` for sparse input vectors if the dense descriptor is also present.
The MR also found and fixes several bugs:
- casting behaviour was incorrect -- all intermediate results were previously cast to the output scalar type. (Now they are first cast to the monoid output domain.)
- the previously implemented version was not asymptotically optimal in case of sparse vectors and/or masks, now fixed.
- not all trivial cases were caught before dispatching. Prior to this MR this was mostly only a …
=> Resolve internal issue #495: fold from sparse vectors into scalars using monoids returns illegal

include/alp/reference/matrix.hpp, include/alp/reference/vector.hpp, include/alp/type_traits.hpp, include/alp/views.hpp
Move all AMFFactory invokations to Matrix constructors
Add type trait that defines new container types with a possibility to modify a single template parameter.
Add vector view type used for gather view on a matrix when one dimension is of size 1 (returning a vector)
Remove redundant get_view implementations
=> 499 Clean up get_view interface

.gitlab-ci.yml, include/graphblas/algorithms/conjugate_gradient.hpp, tests/performance/CMakeLists.txt, tests/performance/performancetests.sh, tests/performance/spmspm.cpp, tests/performance/spmspv.cpp, tests/performance/spmv.cpp
performance tests for spmv, spmspv, and spmspm
=> 419 benchmarking spmv spmspv spmspm

include/graphblas/algorithms/label.hpp, include/graphblas/bsp1d/blas1.hpp, include/graphblas/descriptors.hpp, include/graphblas/reference/blas1.hpp, include/graphblas/reference/io.hpp, tests/smoke/label.cpp, tests/smoke/label_test.cpp, tests/smoke/smoketests.sh, tests/unit/set.cpp
The `grb::set` did not follow out-of-place semantics, while one unit test designed to catch that was bugged. Additionally, the label propagation smoke test relied on the older in-place semantics.
This MR makes sure the existing nonzero structure of the output vector is cleared whenever the dense descriptor is not given. It fixes the corresponding unit test, and replaces the `grb::set( vector, mask, vector )` used by the label propagation algorithm (used for clamping) with the in-place `grb::foldl( vector, mask, vector )` using the `right_assign` operator.
This MR also includes the related changes and fixes listed below.
- Bugfix: introduces the previously missing masked vector-to-vector `grb::foldl` in the BSP1D backend;
- Bugfix: masked vector-to-vector folds with dense vectors but …
=> 533 out of place set does not clear the output vector

include/graphblas/bsp1d/io.hpp, include/graphblas/bsp1d/vector.hpp, include/graphblas/reference/vector.hpp, tests/unit/CMakeLists.txt, tests/unit/doubleAssign.cpp, tests/unit/unittests.sh
Bugfix for the following sequence that previously triggered an assertion failure for the `reference_omp` backend:
```
Vector<double> a(n), b(n);
set(a, 1.2);
set(b, 1.5);
a=b;
a=b; //Fails assertion
```
Issue: multiple-registration of the same container.
Cause: the previous implementation of the copy-assignment seems to predate the introduction of IDs. In its implementation, the container `a` is in fact replaced by a totally new container, with a different ID, through the use of `std::swap` and the creation of a new container within the copy-assignment. Additionally, this induces new memory allocations while in principle a dispatch to `grb::set` would have sufficed.
Solution: dispatch to `grb::set` instead. Apart from the performance gain, this also retains the container's original ID and …
=> 536 copying vector by assignment multiple times fails asserts

include/graphblas/reference/blas1.hpp, tests/unit/launcher/reduce.cpp
The O(n) variant of folding a vector into a scalar that should deal with both sparsity of the vector as well as masks (the so-called fullLoopSparse variant), was in fact not checking for the sparsity of the input vector. All unit tests that could detect this issue were (apparently) instead triggering other variants (i.e., the maskDriven, the vectorDriven, or the dense variant)-- even though unit tests did exist for which the fullLoopSparse variant was triggered, those did not expose the bug detected here.
This MR fixes the bug, and adds a test case that reliably triggers the full sparse loop variant, by using a structural and inverted mask while assuring the sparsity pattern of the vector does not match that of the given (inverted) mask, which thus would also reliably trigger the detected …
=> Resolve internal issue 564: bug in fold from vector to scalar fullloopsparse

include/graphblas/hyperdags/blas3.hpp, tests/unit/zip.cpp
The internal CI builds unit and smoke tests in the `develop` branch (also) using the debug mode (in addition to the standard release mode), which after a totally unrelated commit failed for unit tests that call `eWiseApply` on matrices, for the hyperdags backend only.
The issue was that the output matrix was not correctly registered as a source, resulting in containers being "lost" in the internal hyperdag representation-- for which `src/hyperdags/hyperdag.cpp` has an assertion check. Indeed, assertion checks in sources are only active when compiled in Debug mode, though it remains unclear why those unit tests did not fail before.
=> 106 internal ci picks up assert failure in hyperdags backend

include/graphblas/reference/blas1.hpp, tests/unit/ewiseapply.cpp, tests/unit/unittests.sh
Aristeidis detected that the unit test for `eWiseApply` could fail for some vector lengths that `unittests.sh` never calls it with, and also detected that the sparse-vector driven variant of `eWiseApply` did not correctly check for output mask conditions. The underlying issues were a metabug in the unit test that did not deal properly with vector lengths whose half is an odd number, and a missing negation of the evaluated mask. This MR fixes both issues, and also:
- executes the `eWiseApply` unit test for vectors of length `14`, thus triggering the detecting meta-bug should it ever regress;
- adds to sub-tests to the `eWiseApply` unit test designed to trigger the sparse-vector driven variant with a non-trivial mask that would detect erroneous mask evaluations, thus triggering detection of …
=> Resolves internal issue #577: two bugs related to eWiseApply

include/alp/algorithms/backsubstitution.hpp, tests/smoke/CMakeLists.txt, tests/smoke/alp_backsubstitution.cpp, tests/smoke/smoketests.sh
This is actually the backsubstitution, not the elimination.
=> 574 trsv trsm via gauss jordan elimination

include/graphblas/algorithms/spy.hpp, include/graphblas/reference/matrix.hpp
Alberto detected an erroneous include in the reference `matrix.hpp`, and a missing include in the spy algorithm. This MR fixes both issues. Many thanks for both detecting the bug and for providing the fix!
=> Resolves internal issue #593: dangling include in reference matrix

include/graphblas/hyperdags/blas1.hpp, tests/unit/zip.cpp
Internal CI detects errors in the hyperDAGs backend for the `eWiseApply` and `zip` unit tests, as well as in the `hpcg` smoke test, only when run in debug mode (without `-DNDEBUG`).
Issue: the debug mode detects disconnected hyperDAGs when they are dumped. This indicates a vertex from which there is no path to some output.
Cause: some variants of `eWiseApply` did not connect to the output container as an input to the `eWiseApply`. This sounds paradoxical since this primitive is out of place, but like for the `clear`, the container must still be registered as a source because its previous contents are invalidated. The same issue existed for `unzip`.
This MR fixes both issues, and fixes the code style of the `tests/unit/zip.cpp` unit test.
=> 134 additional internal ci failures triggered for hyperdag in debug mode

NOTICE, include/graphblas/algorithms/mpv.hpp, tests/performance/performancetests.sh, tests/smoke/smoketests.sh
Anders detected an off-by-one error in the mpv (matrix powers) kernel / algorithm, which this MR fixes. This affects the k-NN algorithms as well as the smoke and performance tests based on it, which were previously verified against the sequential ALP/GraphBLAS baseline. This MR also hardens these tests by comparing against a ground truth verified by an external framework, in this case Octave.
This MR has been thoroughly tested using the full test suite. Additionally, an issue (GitHub #136) has been raised to consider an mpv implementation which is not unrolled and simply based on `std::swap`-- suspected is that the current implementation predates supporting swap, and, different from an implementation using `grb::set` instead of swap, a major performance loss compared to an unrolled …
=> 565 k nn and mpv algorithms gives wrong results

include/graphblas/hyperdags/blas3.hpp
The internal CI detected the zip unit test failing for the hyperdags backend, when built in debug release mode.
The cause was that the zip (vector x vector -> matrix), for both pattern and non-pattern matrices did not register the output matrix as a source in the hyperDAG to be generated, thus causing vertices to be "lost". The hyperDAG backend includes an (expensive) sanity check against this, but only when compiled in debug release. This MR fixes the implementation of both matrix zip variants.
=> Fixes bug in HyperDAG backend detected by internal CI

include/graphblas/reference/compressed_storage.hpp, include/graphblas/reference/matrix.hpp, tests/unit/CMakeLists.txt, tests/unit/clearMatrix.cpp, tests/unit/copyVoidMatrices.cpp, tests/unit/unittests.sh
Issue: copy-construction of pattern matrices did not compile.
Cause: In `compressed_storage.hpp` there was a function `copyFrom` specially made for pattern matrices. This has a few template parameters, one is `use_id`. In the other `copyFrom` functions (i.e., the non-pattern specialisation) this has a default value, but for the pattern matrix it does not.
This MR fixes the original compilation error by adding the default value `false` for `use_id` in `copyFrom` for pattern matrices. This template argument is retained so that callees can always assume the same API, regardless of whether pattern matrices are used or not. Furthermore, a unit test that copies pattern matrices into one another has been added, using both `grb::set` and the copy constructor.
This added test then triggered a bug …
=> 507 copy constructor of pattern matrices does not compile

.github/workflows/dbg_smoke.yml, .github/workflows/smoke.yml, .gitlab-ci.yml
A serialised execution of the internal CI could fail due to artifacts expiring. As GitHub issue #146 suggests, this MR increases the artifact time-outs. Sometimes the internal CI picks up errors related to a debug build that are missed by the GitHub CI. As GitHub issue #33 suggests, this MR enables (cheap) debug release checks on the GitHub CI also.
=> 146 33 support serialised internal CI execution and _DEBUG checks on GitHub

include/graphblas/reference/io.hpp
Previously, `grb::set` always accounted for sparsity in both source and destination. This MR exploits when `grb::descriptors::dense` is passed to `grb::set`, and makes sure to never read the input sparsity structure nor to write to the output sparsity structure. This is of course only valid in the unmasked case of `grb::set`.
Furthermore, this MR exploits the use of the dense descriptor if both the destination and source vectors are pattern vectors. Having such vectors that have a dense pattern, again in the unmasked case, makes the `grb::set` a no-op. The same applies when the destination vector is a pattern vector while the dense descriptor was given.
Finally, this MR moves forward an assertion check that if there is only one pattern vector, then this must be the destination vector -- …
=> Speed up several cases of unmasked grb::set when the dense descriptor is given

README.md, include/graphblas/algorithms/kcore_decomposition.hpp
This MR is to resolve GitHub issue #159. It fixes the typo detected by Li Lu, as well as other issues found by perusing the README manually as well as using a spell checker. It additionally fixes one more typo detected by doxygen.
=> Fix various typos

.gitlab-ci.yml, bootstrap.sh, docs/Build_and_test_infra.md, docs/README.md, docs/Run_tests.md, tests/unit/parser.cpp, tests/unit/unittests.sh, tests/unit/utilParserTest.cpp
This PR restructures the internal CI adding several features:
- testing inside a custom Docker container, with pre-compiled LPF and datasets (i.e., easily reproducible builds)
- hence, enabling tests with LPF and datasets
- tests against multiple GCC versions
- task-based description of CI jobs, with full parallelism and minimal dependencies (explicitly written)
@anyzelman This PR should have **high priority**, since a couple of incoming PRs depend on it. At the same time, existing PRs do **not** depend on it.
=> 622 tests depending on datasets are skipped

.gitlab-ci.yml, cmake/CompileFlags.cmake, docs/Build_and_test_infra.md, src/transition/CMakeLists.txt
Minors changes:
- `test-unit_lpf` now requires a `high_core` tagged runner in order to avoid timeout. Fix in [this commit](https://github.com/Algebraic-Programming/ALP/commit/942ad9ffdddf00cfbd57a4ac1e23ec39c41bf375).
- Some tests were skipped during the coverage, it was due to the missing CMake `DATASET_DIR` variable during the build. Fix in [this commit](https://github.com/Algebraic-Programming/ALP/commit/914ddba02b64d0d721d6726fbda5be6487946db8).
- Compilation of sparseblas.cpp was failing when the `reference` backend only was enabled. Fix in [this commit](https://github.com/Algebraic-Programming/ALP/commit/ba7b9261fb6a9f80a9f9b29a13c7f68018694d11).
- Fix sporadic bug of Coverage with OpenMP. See [this gcovr issue](https://github.com/gcovr/gcovr/issues/583#issuecomment-1340762818). Fix …
=> Fix GitLab CI + small improvements

include/graphblas/base/blas3.hpp, include/graphblas/base/io.hpp, include/graphblas/bsp1d/blas2.hpp, include/graphblas/bsp1d/blas3.hpp, include/graphblas/hyperdags/blas2.hpp, include/graphblas/hyperdags/blas3.hpp, include/graphblas/hyperdags/io.hpp, include/graphblas/nonblocking/blas3.hpp, include/graphblas/nonblocking/io.hpp, include/graphblas/reference/blas3.hpp, include/graphblas/reference/io.hpp
The two variants were already implemented in every backend, but not declared in _base_:
- `eWiseApply([out] Matrix, [in] Matrix, [in] Matrix, [in] Monoid, ...)`
- `eWiseApply([out] Matrix, [in] Matrix, [in] Matrix, [in] Operator, ...)`
In order to have a user-friendly interface for all the grb APIs, it would be interesting to declare these variants in _base_ headers.
It would then appear [here](http://albert-jan.yzelman.net/alp/user/group__BLAS3.html).
```c++
RC eWiseApply(
Matrix< OutputType, backend > &C,
const Matrix< InputType1, backend > &A,
const Matrix< InputType2, backend > &B,
const Monoid &mulmono,
const Phase phase = EXECUTE,
const typename std::enable_if< !grb::is_object< OutputType >::value &&
!grb::is_object< InputType1 >::value &&
!grb::is_object< InputType2 >::value && …
```
=> 632 Matrix eWiseApply implemented but not declared in base

include/graphblas/bsp1d/matrix.hpp, include/graphblas/hyperdags/matrix.hpp, include/graphblas/nonblocking/matrix.hpp, tests/unit/CMakeLists.txt, tests/unit/static_asserts/matrix.cpp
Declare the Matrix internal types __value\_type__ and __const\_iterator__ for all backends, as it's already done for the _base_ and _reference_ ones. This would allow the users to consider _base_ as the general interface for a non-specialized usage of grb.
Defined in the [reference backend](https://github.com/Algebraic-Programming/ALP/blob/master/include/graphblas/reference/matrix.hpp#L1864-1872):
```c++
/** @see Matrix::value_type */
typedef D value_type;
/** The iterator type over matrices of this type. */
typedef typename internal::Compressed_Storage<
D, RowIndexType, NonzeroIndexType
>::template ConstIterator<
internal::Distribution< reference >
> const_iterator;
```
=> 629 missing type definitions for multiple backends
